module.exports = {
  apps: [
    {
      name: "proof-service",
      script: "target/release/proof-service",
      cwd: "/home/hendo420/zpump",
      env: {
        RUST_LOG: "info",
        SHIELD_CIRCUIT_PATH: "/home/hendo420/zpump/circuits/shield",
        UNSHIELD_CIRCUIT_PATH: "/home/hendo420/zpump/circuits/unshield",
        TRANSFER_CIRCUIT_PATH: "/home/hendo420/zpump/circuits/transfer",
        SNARKJS_PATH: "npx",
        PORT: "8080",
      },
      error_file: "./logs/proof-service-error.log",
      out_file: "./logs/proof-service-out.log",
      log_file: "./logs/proof-service.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "external-verifier",
      script: "target/release/external-verifier",
      cwd: "/home/hendo420/zpump",
      env: {
        RUST_LOG: "info",
        PORT: "8081",
        EXTERNAL_VERIFIER_PRIVATE_KEY: process.env.EXTERNAL_VERIFIER_PRIVATE_KEY || "",
      },
      error_file: "./logs/external-verifier-error.log",
      out_file: "./logs/external-verifier-out.log",
      log_file: "./logs/external-verifier.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
    },
    {
      name: "frontend",
      script: "npm",
      args: "run dev",
      cwd: "/home/hendo420/zpump/web",
      env: {
        NODE_ENV: "development",
        PORT: "3000",
        NEXT_PUBLIC_SOLANA_RPC_URL: "http://127.0.0.1:8899",
        NEXT_PUBLIC_PROOF_SERVICE_URL: "http://127.0.0.1:8080",
        NEXT_PUBLIC_EXTERNAL_VERIFIER_URL: "http://127.0.0.1:8081",
        NEXT_PUBLIC_INDEXER_URL: "http://127.0.0.1:8082",
        NEXT_PUBLIC_NETWORK: "localnet",
      },
      error_file: "./logs/frontend-error.log",
      out_file: "./logs/frontend-out.log",
      log_file: "./logs/frontend.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
    },
  ],
};

