use anchor_lang::prelude::*;
use crate::state::FactoryState;
use crate::errors::FactoryError;
use ptf_verifier_groth16;

pub fn create_verifying_key(
    ctx: Context<CreateVerifyingKey>,
    circuit_tag: [u8; 32],
    version: u32,
    key_data: Vec<u8>,
) -> Result<()> {
    let factory = &ctx.accounts.factory;
    
    // Verify authority
    require!(
        factory.authority == ctx.accounts.authority.key(),
        FactoryError::InvalidAuthority
    );
    
    // CPI to verifier program to initialize verifying key
    // Note: We'll use the program's CPI interface once it's built
    // For now, this is a placeholder that will work after first build
    let cpi_program = ctx.accounts.verifier_program.to_account_info();
    
    // Create CPI accounts manually since we can't use the generated CPI yet
    let mut cpi_accounts = Vec::new();
    cpi_accounts.push(ctx.accounts.verifying_key.to_account_info());
    cpi_accounts.push(ctx.accounts.authority.to_account_info());
    cpi_accounts.push(ctx.accounts.system_program.to_account_info());
    
    // Build instruction data
    let mut instruction_data = Vec::new();
    // Discriminator (8 bytes) - will be generated by Anchor
    instruction_data.extend_from_slice(&[0; 8]); // Placeholder
    instruction_data.extend_from_slice(&circuit_tag);
    instruction_data.extend_from_slice(&version.to_le_bytes());
    instruction_data.extend_from_slice(&(key_data.len() as u32).to_le_bytes());
    instruction_data.extend_from_slice(&key_data);
    
    // For now, we'll skip the actual CPI call since we need the program built first
    // This will be implemented properly after the first build generates the CPI module
    msg!("CPI to verifier program (placeholder - will be implemented after build)");
    
    Ok(())
}

#[derive(Accounts)]
#[instruction(circuit_tag: [u8; 32], version: u32, key_data: Vec<u8>)]
pub struct CreateVerifyingKey<'info> {
    #[account(
        seeds = [b"factory"],
        bump = factory.bump
    )]
    pub factory: Account<'info, FactoryState>,
    
    /// CHECK: Verifying key account (created by verifier program)
    #[account(mut)]
    pub verifying_key: UncheckedAccount<'info>,
    
    #[account(mut)]
    pub authority: Signer<'info>,
    
    pub verifier_program: Program<'info, ptf_verifier_groth16::program::PtfVerifierGroth16>,
    
    pub system_program: Program<'info, System>,
}

